import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "./provider";
import { ComponentProvider } from "./context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Laboratorio Digital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <ComponentProvider>
            {children}
          </ComponentProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
